import {
  eSummit,
  innobuzz,
  ipl,
  Ted,
  businessModel,
  GoHiking,
  NPF,
  grapixifin,
  homvery,
  igdrones,
  lancyfirm,
  wasper,
  walkingpal,
  tourev,
  sewfin,
  ser,
  FXuav,
  furSphere,
  cosmoinfinitas,
  droove,
  east,
  interno,
  satt,
  Pratikash,
  c2,c1,b3,b2,b1,a1,a2,a3,
  Iit,Kiit,Lnm,Mayanj,Aman,Orissa,Sanskar,SaiKiranIppili,Pratikshya,Arvind,Anisha,Kritye,Suraj,
  Sutej,Teddy,Sonali,Sidrah,Shradha,Roshan,Ramakant,Rahul,Piyush,Payoshni,Payal,Omm,Subham,Harish,Harekrushna,Baishakhi,Angela,Aneek,Aditii,Anauska,Pratyasha,Isita,Anshu,pratyush,sudipta,snehanjali,astha,dinesh,swapnita,pratyasha,ashish,ume,swapna,anannya,abhinab,shahzada,devraj,pragya,
  shwetanjali,rakesh,om,satyashree,yashika,hitesh,shanti,simon,ashirbad,sai,nishant,
} from "../assets";

export const navLinks = [
  {
    id: "home",
    title: "Home",
  },
  {
    id: "about",
    title: "About",
  },
  {
    id: "event",
    title: "Events",
  },
  {
    id: "gallery",
    title: "Gallery",
  },
  {
    id: "ourstar",
    title: "Startups",
  },
  {
    id: "wings",
    title: "Wings",
  },
  {
    id: "testimonials",
    title: "Testimonials",
  },
  {
    id: "contact",
    title: "Contact",
  },
  {
    id: "/team",
    title: "Team",
  },
];
const events = [
  {
    title: "E-Summit",
    icon: eSummit,
    iconBg: "#383E56",
    date: "March 2020 - April 2021",
    points: [
      "Eastern India's biggest flagship event brings together a horde of business moghuls and industry experts to butt heads for the much needed societal changes.",
    ],
    site: "https://www.google.com/",
  },
  {
    title: "TedX",
    // company_name: "Tesla",
    icon: Ted,
    iconBg: "#E6DEDD",
    date: "Jan 2021 - Feb 2022",
    points: [
      "Tedx is a program of local, self organized events that brings in live speakers to combine and indulge in discussions.",
      "TEDx VSSUT is organized annually inviting speakers from distinguished fields who share their experiences and inspire all.",
    ],
    site: "https://www.google.com/",
  },
  {
    title: "Innobuzz",
    icon: innobuzz,
    iconBg: "#383E56",
    date: "Jan 2022 - Jan 2023",
    points: [
      "A 36-hour national level hackathon where participants get a chance to win exciting goodies and cash prizes by submitting effective solutions to a problem statement.",
    ],
    site: "https://www.google.com/",
  },
  {
    title: "Business Model",
    // company_name: "Meta",
    icon: businessModel,
    iconBg: "#E6DEDD",
    date: "Jan 2023 - Present",
    points: [
      "Business Model competition is a platform where various startups pitch in there ideas to tackle day to day problems infront of genuine investors who guide them during and even after the event.",
    ],
    site: "https://www.google.com/",
  },
  {
    title: "Ipl Auction",
    // company_name: "Meta",
    icon: ipl,
    iconBg: "#E6DEDD",
    date: "Jan 2023 - Present",
    points: [
      "A fun event where participants place themselves in the shoes of a bidder to build a dream team they always thought of. Team with the best bargaining and bidding skills wins",
    ],
    site: "https://www.google.com/",
  },
];

const startups = [
  {
    name: "Homevery",
    site: "https://www.homvery.com/",
    about:
      "Homvery provides with all the services that one needs in Day to Day life like Electrician,Plumber, Painter etc.",
    url: homvery,
  },
  {
    name: "IG Drones",
    site: "https://igdrones.com/",
    about:
      " IG Drones is setting new standards in delivering solution using AI,ML, Satellite Imagery,Big Data etc to domain specific Industries.",
    url: igdrones,
  },
  {
    name: "Wasper",
    site: "https://www.homvery.com/",
    about:
      "Were a team of tech-savvy marketing pros with a passion for helping local D2C brands expand into online ventures, scaletheir operations to serve Pan India, and get them onto e-commerce marketplaces",
    url: wasper,
  },
  {
    name: "WalkingPal",
    site: "https://www.walkingpal.in/",
    about:
      " IG Drones is setting new standards in delivering solution using AI,ML, Satellite Imagery,Big Data etc to domain specific Industries.",
    url: walkingpal,
  },
  {
    name: "Navonmesh Prashar Foundation",
    site: "https://navprasar.org/",
    about:
      "Navonmesh Prashan Empowers students and youth helping them communicate and connect with the Rural Areas to bridge the gap between Innovation and Society.",
    url: NPF,
  },
  {
    name: "furSphere",
    site: "/",
    about: " The go-to companion platform for all pet needs and adoption",
    url: furSphere,
  },
  {
    name: "Lancyfirm",
    site: "https://lancyfirm.in/",
    about:
      "We are a unit of enthusiasts gathered under a single banner to structure our perception of freelancing.",
    url: lancyfirm,
  },
  {
    name: "SEW",
    site: "https://www.sew4all.in/",
    about:
      " S.E.W is a box full of knowledge and ideas which has the potential to wave the mind of the child towards learning.",
    url: sewfin,
  },
  {
    name: "FxUAV",
    site: "/",
    about:
      "This is a startup which aims to solve the fire problem in the best possible way.",
    url: FXuav,
  },
  {
    name: "Tourev",
    site: "/",
    about:
      " Tourev is a startup that envisions and aims at providing services related to picnic, camping and other tourist activities.",
    url: tourev,
  },
  {
    name: "Droove",
    site: "https://www.homvery.com/",
    about:
      " An E-Vehicle Rental platform which allows you to Rent an E-vehicle at your fingertips in an very affordable price as well as we are also working for inhouse E- bike , which is currently in POC stage .",
    url: droove,
  },
  {
    name: "GoHiking",
    site: "/",
    about: " One stop solution for your all adventure needs.",
    url: GoHiking,
  },
  {
    name: "Servicescape",
    site: "/",
    about:
      "Servicescape creates a supply chain using the blockchain technology.",
    url: ser,
  },
  {
    name: "Graphixi",
    site: "https://grapixi.in/",
    about:
      "We are a unit of enthusiasts gathered under a single banner to structure our perception of freelancing.",
    url: grapixifin,
  },
  {
    name: "CosmoInfinitas",
    site: "https://cosmoinfinitas.tech/",
    about:
      "CosmoInfinitas is an Metaverse and a NFT Marketplace which is build on top of Ethereum Blockchain.",
    url: cosmoinfinitas,
  },
];

const wings = [
  {
    title: "InternO",
    about:
      "InternO intends to provide students with internships in successful startups. We have proudly collaborated with 17 companies and counting for more",
    url: interno,
  },
  {
    title: "Entrepreneurship Accords and Startup growth Traffic",
    about:
      "Collaborates with all other E-Cells to foster Entrepreneurship activities and enhance the prevalent startup culture.",
    url: east,
  },
  {
    title: "Startup Accelaration Think Tank",
    about:
      "Start-up acceleration, development, enhancement programs and think tank to inoculate startup ideas.",
    url: satt,
  },
];
const teams = {
  lead: [
    {
      name: "Anshu Agrawal",
      designation: "Co-ordinator",
      url: Anshu,
      ilink: "#",
      flink: "#",
      llink: "https://www.linkedin.com/in/anshu-agrawal-b517b9244/",
      tlink: "https://twitter.com/008Anshu",
    },
    {
      name: "Shradha Mohapatra ",
      designation: "Co-ordinator ",
      url: Shradha,
      ilink: "https://instagram.com/__shradha_032?igshid=Y2M0YTlkZGNmOQ==",
      flink: "#",
      llink: "https://www.linkedin.com/in/shradha-mohapatra-818b05238",
      tlink: "#",
    },
    {
      name: "Suraj Mahapatra ",
      designation: "Co-lead Graphic Designing",
      url: pratyush,
      ilink: "https://www.instagram.com/_.suruuuu._/?utm_source=qr",
      flink: "#",
      llink: "https://www.linkedin.com/in/suraj052",
      tlink: "https://twitter.com/SurajM052",
    },
    {
      name: "Pratikash Panda",
      designation: "Co-ordinator",
      url: Pratikash,
      ilink: "#",
      flink: "#",
      llink: "#",
      tlink: "#",
    },
  ],
  member: [
    {
      name: "Sai Kiran Ippili",
      designation: "Social Media",
      url: SaiKiranIppili,
      ilink: "https://www.instagram.com/iamsaikiranippili/",
      flink: "https://facebook.com/100010919206372",
      llink: "https://linkedin.com/in/saikiranippili",
      tlink: "https://twitter.com/intent/follow?screen_name=ippilisaikiran",
    },
    {
      name: "Sanskar Patra",
      designation: "Event Management",
      url: Sanskar,
      ilink: "https://instagram.com/crazy_anyone16052003?igshid=NGExMmI2YTkyZg==",
      flink: "https://www.facebook.com/sanskar.patra.16?mibextid=ZbWKwL",
      llink: "https://www.linkedin.com/in/sanskar-patra-675517186",
      tlink: "https://twitter.com/SskrPtra1",
    },
    {
      name: "Arvind Dora",
      designation: "Public Relations",
      url: Arvind,
      ilink: "#",
      flink: "#",
      llink: "#",
      tlink: "#",
    },
    {
      name: "Krityee Subhadarshini",
      designation: "Graphic Designing",
      url: Kritye,
      ilink: "https://instagram.com/krityee?igshid=OTk0YzhjMDVlZA==",
      flink: "#",
      llink: "https://www.linkedin.com/in/krityee-subhadarshini-9441621b9",
      tlink: "#",
    },
    {
      name: "Pratikshya Behera ",
      designation: "Public Relations",
      url: Pratikshya,
      ilink: "#",
      flink: "#",
      llink: "#",
      tlink: "#",
    },
    {
      name: "Anisha Mishra",
      designation: "Event Management",
      url: Anisha,
      ilink: "https://instagram.com/_anisha.03_?igshid=MzNlNGNkZWQ4Mg==",
      flink: "https://www.facebook.com/anisha.mishra.367?mibextid=ZbWKwL",
      llink: "https://www.linkedin.com/in/anisha-mishra/",
      tlink: "#",
    },
    {
      name: "Anshu Agrawal",
      designation: "Tech Member",
      url: Anshu,
      ilink: "#",
      flink: "#",
      llink: "https://www.linkedin.com/in/anshu-agrawal-b517b9244/",
      tlink: "https://twitter.com/008Anshu",
    },
    {
      name: "Nikunj Agrawal",
      designation: "Tech Member",
      url: Pratikash,
      ilink: "#",
      flink: "#",
      llink: "#",
      tlink: "#",
    },
    {
      name: "Aneek Guha",
      designation: "Tech Member",
      url: Aneek,
      ilink: "https://instagram.com/aneek9051?igshid=NTc4MTIwNjQ2YQ==",
      flink: "#",
      llink: "https://www.linkedin.com/in/aneek-guha-675589221",
      tlink: "#",
    },
    {
      name: "Harish Choudhary",
      designation: "Tech Member",
      url: Harish,
      ilink: "#",
      flink: "https://www.facebook.com/harish.choudhary.758737?mibextid=ZbWKwL",
      llink: "https://www.linkedin.com/in/harish-choudhary-636123201",
      tlink: "#",
    },
    {
      name: "Rahul Krishna Nanda ",
      designation: "Marketing and Outreach ",
      url: Rahul,
      ilink: "https://instagram.com/rahulknanda?igshid=MzNlNGNkZWQ4Mg==",
      flink: "#",
      llink: "https://www.linkedin.com/in/rkn26",
      tlink: "#",
    },
    {
      name: "Angela Kundoo",
      designation: "Event management & public relations ",
      url: Angela,
      ilink: "#",
      flink: "#",
      llink: "#",
      tlink: "#",
    },
    {
      name: "Piyush Sahu",
      designation: "Social Media ",
      url: Piyush,
      ilink: "https://instagram.com/itz_piyush03_?igshid=NGExMmI2YTkyZg==",
      flink: "#",
      llink: "https://www.linkedin.com/in/piyush-sahu-36a859227",
      tlink: "#",
    },
    {
      name: "Aditi Dora",
      designation: "Marketing and Sponsorship",
      url: Aditii,
      ilink: "https://instagram.com/__.aaaditiiii.__?igshid=NTc4MTIwNjQ2YQ==",
      flink: "#",
      llink: "https://www.linkedin.com/in/aditi-dora-b8307022b?trk=contact-info",
      tlink: "#",
    },
    {
      name: "Shashwata Maharana",
      designation: "Graphic Designing",
      url: Teddy,
      ilink: "https://instagram.com/shswta_?igshid=ZGUzMzM3NWJiOQ==",
      flink: "#",
      llink: "https://www.linkedin.com/in/shashwata-maharana-810786240",
      tlink: "#",
    },
    {
      name: "Sutej Patra",
      designation: "Event Management ",
      url: Sutej,
      ilink: "https://instagram.com/sutejpatra?igshid=OGQ5ZDc2ODk2ZA==",
      flink: "#",
      llink: "https://www.linkedin.com/in/sutej-patra-2842a9231",
      tlink: "#",
    },
    {
      name: "Subham Kumar Rout ",
      designation: "PR & Social Media Management ",
      url: Subham,
      ilink: "https://instagram.com/_subhamrout?igshid=ZDc4ODBmNjlmNQ==",
      flink: "#",
      llink: "https://www.linkedin.com/in/subham-rout-332b04210",
      tlink: "#",
    },
    {
      name: "Roshan Agrawal",
      designation: "Event Management",
      url: Roshan,
      ilink: "http://instagram.com/roshan_05.09",
      flink: "#",
      llink: "https://www.linkedin.com/in/2003roshanag",
      tlink: "#",
    },
    {
      name: "Pratyasha Priyadarshini ",
      designation: "Graphic designing ",
      url: Pratyasha,
      ilink: "https://instagram.com/khuuushi._?igshid=ZDc4ODBmNjlmNQ==",
      flink: "#",
      llink: "https://www.linkedin.com/in/pratyasha-priyadarshini-5a1669240",
      tlink: "#",
    },
    {
      name: "Payal Sahoo ",
      designation: "Social Media ",
      url: Payal,
      ilink: "https://instagram.com/payal_sahoo_?igshid=OTk0YzhjMDVlZA==",
      flink: "#",
      llink: "https://www.linkedin.com/in/payal-sahoo-829866236",
      tlink: "#",
    },
    {
      name: "Ramakanta Sahoo",
      designation: "Marketing and Sponsorship ",
      url: Ramakant,
      ilink: "",
      flink: "#",
      llink: "https://www.linkedin.com/in/ramakantsahoo",
      tlink: "#",
    },
    {
      name: "Anauska Das ",
      designation: "Marketing and sponsorship ",
      url: Anauska,
      ilink: "#",
      flink: "#",
      llink: "http://www.linkedin.com/in/anauska-das-a26aa8235",
      tlink: "#",
    },{
      name: "Sidrah Kamal",
      designation: "Public Relations",
      url: Sidrah,
      ilink: "https://instagram.com/sidrah_kamal?igshid=MzNlNGNkZWQ4Mg==",
      flink: "#",
      llink: "https://www.linkedin.com/in/sidrah-kamal-b61690220",
      tlink: "#",
    },
    {
      name: "Omm Pani ",
      designation: "Marketing and sponsorship ",
      url: Omm,
      ilink: "https://www.instagram.com/omm.pani",
      flink: "#",
      llink: "https://www.linkedin.com/in/omm-pani-608a4a248",
      tlink: "#",
    },
    {
      name: "Payoshni Behera ",
      designation: "Public Relations ",
      url: Payoshni,
      ilink: "https://instagram.com/b__payoshni?igshid=ZDc4ODBmNjlmNQ==",
      flink: "#",
      llink: "https://www.linkedin.com/in/payoshni-behera-9659b1227",
      tlink: "#",
    },
    {
      name: "Isita Naik",
      designation: "PR and MNS",
      url: Isita,
      ilink: "https://instagram.com/ishita__n?igshid=MzNlNGNkZWQ4Mg==",
      flink: "#",
      llink: "https://www.linkedin.com/in/ishita-n-144a7b264",
      tlink: "#",
    },
    {
      name: "Baishakhi Guin",
      designation: "PR & Event Management ",
      url: Baishakhi,
      ilink: "https://instagram.com/guin.baishakhi?igshid=ZGUzMzM3NWJiOQ==",
      flink: "#",
      llink: "https://www.linkedin.com/in/baishakhi-guin-809592240",
      tlink: "#",
    },
    {
      name: "Sonali Sahoo",
      designation: "Graphic Designing",
      url: Sonali,
      ilink: "https://www.instagram.com/_simply.sona_/?next=%2F",
      flink: "#",
      llink: "https://www.linkedin.com/in/sonali-sahoo-2ab699221/",
      tlink: "#",
    },
    {
      name: "A Harekrushna Nayak ",
      designation: "Tech",
      url: Harekrushna,
      ilink: "#",
      flink: "#",
      llink: "#",
      tlink: "#",
    },
  ],

  Jmember: [
    {
      name: "Pratyush Panda",
      designation: "Social Media & Technical Domain",
      url: pratyush,
      ilink: "https://www.instagram.com/iamsaikiranippili/",
      flink: "https://facebook.com/100010919206372",
      llink: "https://linkedin.com/in/saikiranippili",
      tlink: "https://twitter.com/intent/follow?screen_name=ippilisaikiran",
    },
    {
      name: "Nishant Kumar Singh",
      designation: "Event management ",
      url: nishant,
      ilink: "https://www.instagram.com/iamsaikiranippili/",
      flink: "https://facebook.com/100010919206372",
      llink: "https://linkedin.com/in/saikiranippili",
      tlink: "https://twitter.com/intent/follow?screen_name=ippilisaikiran",
    },
    {
      name: "Pratyasha Panda",
      designation: "Marketing and Sponsorship ",
      url: pratyasha,
      ilink: "https://www.instagram.com/iamsaikiranippili/",
      flink: "https://facebook.com/100010919206372",
      llink: "https://linkedin.com/in/saikiranippili",
      tlink: "https://twitter.com/intent/follow?screen_name=ippilisaikiran",
    },
    {
      name: "Rakesh Kumar Barick ",
      designation: "Marketing and Sponsorship",
      url: rakesh,
      ilink: "https://www.instagram.com/iamsaikiranippili/",
      flink: "https://facebook.com/100010919206372",
      llink: "https://linkedin.com/in/saikiranippili",
      tlink: "https://twitter.com/intent/follow?screen_name=ippilisaikiran",
    },
    {
      name: "Swapnita Singh",
      designation: "Public Relations",
      url: swapnita,
      ilink: "https://www.instagram.com/iamsaikiranippili/",
      flink: "https://facebook.com/100010919206372",
      llink: "https://linkedin.com/in/saikiranippili",
      tlink: "https://twitter.com/intent/follow?screen_name=ippilisaikiran",
    },
    {
      name: "Pragya Paramita Pattnayak",
      designation: "Graphic Designing",
      url: pragya,
      ilink: "https://www.instagram.com/iamsaikiranippili/",
      flink: "https://facebook.com/100010919206372",
      llink: "https://linkedin.com/in/saikiranippili",
      tlink: "https://twitter.com/intent/follow?screen_name=ippilisaikiran",
    },
    {
      name: "Ume Habibba",
      designation: "Marketing and Sponsorship ",
      url: ume,
      ilink: "https://www.instagram.com/iamsaikiranippili/",
      flink: "https://facebook.com/100010919206372",
      llink: "https://linkedin.com/in/saikiranippili",
      tlink: "https://twitter.com/intent/follow?screen_name=ippilisaikiran",
    },
    {
      name: "Shahzada Musharraf",
      designation: "Marketing and sponsorship ",
      url: shahzada,
      ilink: "https://www.instagram.com/iamsaikiranippili/",
      flink: "https://facebook.com/100010919206372",
      llink: "https://linkedin.com/in/saikiranippili",
      tlink: "https://twitter.com/intent/follow?screen_name=ippilisaikiran",
    },
    {
      name: "Hitesh Kumar Palo ",
      designation: "Marketing and sponsorship ",
      url: hitesh,
      ilink: "https://www.instagram.com/iamsaikiranippili/",
      flink: "https://facebook.com/100010919206372",
      llink: "https://linkedin.com/in/saikiranippili",
      tlink: "https://twitter.com/intent/follow?screen_name=ippilisaikiran",
    },
    {
      name: "Shwetanjali Gagaria",
      designation: "Social Media",
      url: shwetanjali,
      ilink: "https://www.instagram.com/iamsaikiranippili/",
      flink: "https://facebook.com/100010919206372",
      llink: "https://linkedin.com/in/saikiranippili",
      tlink: "https://twitter.com/intent/follow?screen_name=ippilisaikiran",
    },
    {
      name: "Dinesh Pinninti",
      designation: "Public Relations and Content Writing",
      url: dinesh,
      ilink: "https://www.instagram.com/iamsaikiranippili/",
      flink: "https://facebook.com/100010919206372",
      llink: "https://linkedin.com/in/saikiranippili",
      tlink: "https://twitter.com/intent/follow?screen_name=ippilisaikiran",
    },
    {
      name: "SNEHANJALI GAGARIA ",
      designation: "Public Relation ",
      url: snehanjali,
      ilink: "https://www.instagram.com/iamsaikiranippili/",
      flink: "https://facebook.com/100010919206372",
      llink: "https://linkedin.com/in/saikiranippili",
      tlink: "https://twitter.com/intent/follow?screen_name=ippilisaikiran",
    },
    {
      name: "Yashika Sharma ",
      designation: "Technical ",
      url: yashika,
      ilink: "https://www.instagram.com/iamsaikiranippili/",
      flink: "https://facebook.com/100010919206372",
      llink: "https://linkedin.com/in/saikiranippili",
      tlink: "https://twitter.com/intent/follow?screen_name=ippilisaikiran",
    },
    {
      name: "Om Shree Pradhan ",
      designation: "Event management ",
      url: om,
      ilink: "https://www.instagram.com/iamsaikiranippili/",
      flink: "https://facebook.com/100010919206372",
      llink: "https://linkedin.com/in/saikiranippili",
      tlink: "https://twitter.com/intent/follow?screen_name=ippilisaikiran",
    },
    {
      name: "Sudipta Padhi",
      designation: "Public Relation ",
      url: sudipta,
      ilink: "https://www.instagram.com/iamsaikiranippili/",
      flink: "https://facebook.com/100010919206372",
      llink: "https://linkedin.com/in/saikiranippili",
      tlink: "https://twitter.com/intent/follow?screen_name=ippilisaikiran",
    },
    {
      name: "Shanti Sworup Biswal ",
      designation: "Technical ",
      url: shanti,
      ilink: "https://www.instagram.com/iamsaikiranippili/",
      flink: "https://facebook.com/100010919206372",
      llink: "https://linkedin.com/in/saikiranippili",
      tlink: "https://twitter.com/intent/follow?screen_name=ippilisaikiran",
    },
    {
      name: "Abhinab Banka",
      designation: "Video Editing ",
      url: abhinab,
      ilink: "https://www.instagram.com/iamsaikiranippili/",
      flink: "https://facebook.com/100010919206372",
      llink: "https://linkedin.com/in/saikiranippili",
      tlink: "https://twitter.com/intent/follow?screen_name=ippilisaikiran",
    },
    {
      name: "Ashirbad Tripathy",
      designation: "Public Relations",
      url: ashirbad,
      ilink: "https://www.instagram.com/iamsaikiranippili/",
      flink: "https://facebook.com/100010919206372",
      llink: "https://linkedin.com/in/saikiranippili",
      tlink: "https://twitter.com/intent/follow?screen_name=ippilisaikiran",
    },
    { 
      name: "Simon Kenny Panigrahi",
      designation: "Public Relations",
      url: simon,
      ilink: "https://www.instagram.com/iamsaikiranippili/",
      flink: "https://facebook.com/100010919206372",
      llink: "https://linkedin.com/in/saikiranippili",
      tlink: "https://twitter.com/intent/follow?screen_name=ippilisaikiran",
    },
    { 
      name: "Satyashree Dash",
      designation: "Graphic Designing",
      url: satyashree,
      ilink: "https://www.instagram.com/iamsaikiranippili/",
      flink: "https://facebook.com/100010919206372",
      llink: "https://linkedin.com/in/saikiranippili",
      tlink: "https://twitter.com/intent/follow?screen_name=ippilisaikiran",
    },
    { 
      name: "Debaraj Beura ",
      designation: "Event Management, Marketing N Sponsorship ",
      url: "",
      ilink: "https://www.instagram.com/iamsaikiranippili/",
      flink: "https://facebook.com/100010919206372",
      llink: "https://linkedin.com/in/saikiranippili",
      tlink: "https://twitter.com/intent/follow?screen_name=ippilisaikiran",
    },
    { 
      name: "Abhisek Behera",
      designation: "Event Management ",
      url :"",
      ilink: "https://www.instagram.com/iamsaikiranippili/",
      flink: "https://facebook.com/100010919206372",
      llink: "https://linkedin.com/in/saikiranippili",
      tlink: "https://twitter.com/intent/follow?screen_name=ippilisaikiran",
    },
    { 
      name: "SWAPNA Sarthak Mohapatra ",
      designation: "Social Media ",
      url: swapna,
      ilink: "https://www.instagram.com/iamsaikiranippili/",
      flink: "https://facebook.com/100010919206372",
      llink: "https://linkedin.com/in/saikiranippili",
      tlink: "https://twitter.com/intent/follow?screen_name=ippilisaikiran",
    },
    { 
      name: "Sai sidharth dash",
      designation: "Marketing and sponsorship ",
      url: sai,
      ilink: "https://www.instagram.com/iamsaikiranippili/",
      flink: "https://facebook.com/100010919206372",
      llink: "https://linkedin.com/in/saikiranippili",
      tlink: "https://twitter.com/intent/follow?screen_name=ippilisaikiran",
    },
    { 
      name: "Ashish Pradhan",
      designation: "Graphic Design ",
      url: ashish,
      ilink: "https://www.instagram.com/iamsaikiranippili/",
      flink: "https://facebook.com/100010919206372",
      llink: "https://linkedin.com/in/saikiranippili",
      tlink: "https://twitter.com/intent/follow?screen_name=ippilisaikiran",
    },
    
  ]
};

const GalleryData = [
  {
      id:1,
      titile:"TedX",
      image:a1
  },
  {
      id:2,
      titile:"TedX",
      image:a2
  },
  {
      id:3,
      titile:"TedX",
      image:a3
  },
  {
      id:4,
      titile:"Innobuzz",
      image:b1
  },
  {
      id:5,
      titile:"Innobuzz",
      image:b2
  },
  {
      id:6,
      titile:"Innobuzz",
      image:b3
  },
  {
      id:7,
      titile:"Family",
      image:c1
  },
  {
      id:8,
      titile:"Family",
      image:c2
  },
]
 
const Testimonials=[
  {
    name:'KIIT TBI',
    url:Kiit,
    caption:'Bhubaneshwar',
    details:'EcellVSSUT will act an essential element for the future of startups and Entrepreneurship in the near future',
  },
  {
    name:'Aman Dhattarwal',
    url:Aman,
    caption:'Founder of Apni Kaksha',
    details:'Tedx of VSSUT is better than that of IIT Guhawati.',
  },
  {
    name:'Mayank Rajput',
    url:Mayanj,
    caption:'CEO at RoboManiax EduTech Pvt. Ltd.',
    details:'A superb team and a fantastic work culture make up E-cell VSSUT. Looking forward to collaboration with this body.',
  },
  {
    name:'Shri L N Mishra',
    url:Lnm,
    caption:'Former Director of MCL',
    details:'E-Cell VSSUT Burla truely deserves personal appreciation . The kind of start-ups they have establishe within this short time is remarkable.',
  },
  {
    name:'Dean',
    url:Iit,
    caption:'RMSOEE IIT Kharagpur',
    details:'A very young Entrepreneurship Cell with a very healthy start-up culture.',
  },
  {
    name:'OrissaPost',
    url:Orissa,
    caption:'',
    details:'An amazing and engaging student society of Odisha where young engineering undergrads generate ideas quite refreshing with a vision for social change.',
  }
]



export { events, startups, wings, teams,GalleryData, Testimonials };
